### ISSUE TITLE
How to obtain results of figure 5?

### ISSUE THREAD

**Issue by Pixie412** [wz7in/CVPR2023-VLSAT#8]
Hi,

Thanks for the great work. I have some question about figure 5. 
1. How to parse the description of scanrefer? Do you need to align the description of scanrefer to the annotation of 3DSSG dataset?
2. Do the model directly perform inference on scannet without training?

**Comment by yang1332133** [comment]
> Hi,
> 
> Thanks for the great work. I have some question about figure 5.
> 
> 1. How to parse the description of scanrefer? Do you need to align the description of scanrefer to the annotation of 3DSSG dataset?
> 2. Do the model directly perform inference on scannet without training?

hi！Do you know how Figure 4 in the paper is visualized

**Comment by wz7in** [comment]
1. We use the classifier training on 3DSSG without fine-tuning, so the relationship classes are the same as it during inference on ScanRef2. We use language scene graph parser to get the ground truth on ScanNet, we align the relationship with 26 Classes in 3DSSG by computing feature similarities. Since we just visualize some cases, we also correct the above alignment results by man crafting.在 2023年7月12日，20:20，yang1332133 ***@***.***> 写道：﻿

Hi,
Thanks for the great work. I have some question about figure 5.

How to parse the description of scanrefer? Do you need to align the description of scanrefer to the annotation of 3DSSG dataset?
Do the model directly perform inference on scannet without training?


hi！Do you know how Figure 4 in the paper is visualized
